added components for future use
Jagadguru-Kripaluji-Yog/JKYog_2.0 pull request #36
Opened 2024-02-20 08:58 UTC by oleeh-shd

2024-02-24 20:52 UTC, PranayPant commented on src/components/info-card-small/index.tsx
@oleeh-shd Can we use the base component `src/components/Card` here instead? All the styles are already on that component so we don't need to duplicate that. We could just pass in the title and description as props. See the  storybook for examples.

Also, why is the image and the text in separate cards next to each other?

2024-02-24 20:52 UTC, PranayPant commented on src/components/button/button.tsx
> +        ${classes}
shouldn't we apply the `classes` prop even if its not of type `link`?

2024-02-26 21:09 UTC, PranayPant requested changes

2024-02-26 21:09 UTC, PranayPant commented on src/components/button/button.tsx
> +        ${classes}
@oleeh-shd We already have a `className` prop, I think from extending from the `ButtonHTMLAttributes<HTMLButtonElement>`. We don't actually need the `classes` prop.

2024-02-26 21:09 UTC, PranayPant commented on src/components/button/button.tsx
> +        ${classes}
@oleeh-shd Let us use `cn` utility to join all the classes.

2024-02-27 09:45 UTC, oleeh-shd commented on src/components/info-card-small/index.tsx
This component looks different than our current `src/components/Card` .  Image and the text in separate cards next to each other because it is on design, that why I've created it as separate component

![image](https://github.com/Jagadguru-Kripaluji-Yog/JKYog_2.0/assets/98888856/dd799d08-5c34-4060-811d-6fc4a3a8f00c)

2024-02-27 10:36 UTC, oleeh-shd commented on src/components/button/button.tsx
> +        ${classes}
@PranayPant I need to pass `classes` prop to `<Button /> ` component no matter it is `link` or `button` type. So I've implemented `classes` prop for both types. Do you mean we should use  `classes` for  `link` type and `className ` for `button` type?

2024-02-27 16:09 UTC, PranayPant commented on src/components/info-card-small/index.tsx
@oleeh-shd I was thinking it would make more sense for those two be two separate components. The one on the left can just be an `<Image />` wrapped in a `<div>`, not sure if that needs to be its own component. The one the right should use the `<Card />` component, I made a [PR](https://github.com/Jagadguru-Kripaluji-Yog/JKYog_2.0/pull/39)to show how we can achieve that without re-implementation. Note that we can always customize the default `height/width` and content spacing as needed via the `containerClasses` and `contentClasses` respectively.

2024-02-27 21:14 UTC, PranayPant approved these changes

2024-02-27 21:16 UTC, merged